version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: wp-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Digital_GxP@2023
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp
      MYSQL_PASSWORD: Digital_GxP@2023
    networks:
      - wpsite
  
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '3001:80'
    environment:
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: Digital_GxP@2023
    networks:
      - wpsite

  #WordPress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp-web
    ports:
      - "3000:80"
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: Digital_GxP@2023
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: {}