version: "3.9"

# networks:
#   wordpress:

services:
  #MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  #Wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 3000:80
    env_file:
      - ./.env
    environment:
      UPLOAD_LIMIT: 64M
      WORDPRES_DB_HOST: ${DB_HOST}
      WORDPRES_DB_NAME: ${MYSQL_DATABASE}
      WORDPRES_DB_USER: ${MYSQL_USER}
      WORDPRES_DB_PASSWORD: ${MYSQL_PASSWORD}
    working_dir: /var/www/html/blog
    volumes:
      - ./wordpress:/var/www/html/blog
      - ./.htaccess:/var/www/html/.htaccess
      - ./index.php:/var/www/html/index.php
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    # restart: always
    ports:
      - 3001:80
    environment:
      PMA_HOST: mysql:3306
      UPLOAD_LIMIT: 64M
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  mysql-data:
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: './db-data'
