version: "3.9"

# networks:
#   wordpress:

services:
  #Nginx server for WordPress
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    env_file:
      - ./.env
    depends_on:
      - mysql
      - wordpress
    # restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./wordpress:/var/www/html

  #MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    # restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    image: wordpress:6.1-fpm-alpine
    container_name: wordpress
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 3002:80
    env_file:
      - ./.env
    environment:
      UPLOAD_LIMIT: 64M
      WORDPRES_DB_HOST: ${DB_HOST}
      WORDPRES_DB_NAME: ${MYSQL_DATABASE}
      WORDPRES_DB_USER: ${MYSQL_USER}
      WORDPRES_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./wordpress:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      


  # #PHP
  # php:
  #   build:
  #     context: .
  #     dockerfile: php.dockerfile
  #   container_name: php
  #   env_file:
  #     - ./.env
  #   environment:
  #     UPLOAD_LIMIT: 64M
  #   # restart: always
  #   volumes:
  #     - ./wordpress:/var/www/html:delegated
  #     - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    # restart: always
    ports:
      - 3001:80
    environment:
      PMA_HOST: mysql:3306
      UPLOAD_LIMIT: 64M
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

volumes:
  db-data:
    # driver: local
    # driver_opts:
    #   type: 'none'
    #   o: 'bind'
    #   device: './db-data'
