version: '3.9'

networks:
  wordpress:

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    env_file:
      - ./.env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated

  #MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql
    # volumes:
      # - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    # networks:
    #   - wordpress

  #PHP
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    env_file:
      - ./.env
    volumes:
      - ./wordpress:/var/www/html:delegated
    # networks:
    #   - wordpress
  
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '3001:80'
    environment:
      PMA_HOST: mysql:3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # networks:
    #   - wordpress

  #WordPress
  # wordpress:
  #   depends_on:
  #     - db
  #   image: wordpress:latest
  #   container_name: wp-web
  #   ports:
  #     - "3000:80"
  #   restart: always
  #   volumes: ['./wordpress:/var/www/html']
  #   environment:
  #     WORDPRESS_DB_HOST: db:3306
  #     WORDPRESS_DB_USER: wp
  #     WORDPRESS_DB_PASSWORD: Digital_GxP@2023
  #     WORDPRESS_DB_NAME: wordpress
  #   networks:
  #     - wpsite

# volumes:
#   db_data: {}